export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";
export const ADD_POST_TO_BOOKMARK = "ADD_POST_TO_BOOKMARK";
export const REMOVE_POST_FROM_BOOKMARK = "REMOVE_POST_FROM_BOOKMARK";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
